#
spring:
  application:
    name: springSecurityDemo
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/wayne?serverTimezone=UTC&useSSL=false
    username: wayne
    password: djw131939AA!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
server:
  port: 8089
